version: 2
updates:
 - package-ecosystem: pip
   directory: "/"
   schedule:
     interval: daily
     time: "22:00"
     # Specify JST (Japan Standard Time) as time zone
     timezone: "Asia/Tokyo"
   open-pull-requests-limit: 10
